
title: "Servicios de Bienvenida"
description: "Estás en buenas manos en la Ciudad de Guatemala"
url: "https://serviciosdebienvenida.com"
baseurl: ""
logo: "/assets/images/logo_servicios_de_bienvenida_web.png"

author:
  name: Servicios de Bienvenida
  bio: "Apasionados por hacer que tu experiencia en el corazón de la Ciudad de Guatemala sea inolvidable."
  links:
    - label: "Instagram"
      url: "https://www.instagram.com/serviciosdebienvenida"
    - label: "Facebook"
      url: "https://www.facebook.com/serviciosdebienvenida"
    - label: "WhatsApp"
      url: "https://wa.me/502"

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache
