
title: "Servicios de Bienvenida"
description: "Estás en buenas manos en la Ciudad de Guatemala"
url: "https://serviciosdebienvenida.com"
baseurl: ""
logo: "/assets/images/logo_servicios_de_bienvenida_web.png"

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: default
search: true

markdown: kramdown

# Author settings
author:
  name: "Servicios de Bienvenida"
  bio: "Apasionados por hacer que tu experiencia en el corazón de la Ciudad de Guatemala sea inolvidable."
  avatar: "/assets/images/bio-photo.jpg"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/serviciosdebienvenida"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/profile.php?id=61577256517959"
    - label: "WhatsApp"
      icon: "fab fa-fw fa-whatsapp"
      url: "https://wa.me/502"

# Footer links (optional)
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/serviciosdebienvenida"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/profile.php?id=61577256517959"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
